package:
  name: torcharrow
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  path: "{{ environ.get('SOURCE_ROOT_DIR') }}"

requirements:
  build:
    - cmake
    - python
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - typing_inspect
    - pandas
    - typing
    - tabulate
    - pyarrow
    - arrow-cpp==8.0.0
    - cffi
    - libsodium
    - libevent
    - bzip2
    - lz4-c
    {% if osx %}
    - glog==0.6.0
    - libboost
    {% elif linux %}
    - glog==0.4.0
    - libboost==1.71.0
    - double-conversion
    # - re2==2020.01.01
    {% endif %}


build:
  string: py{{py}}
  script_env:
    - BUILD_VERSION
    - CPU_TARGET
    - PYTHON_VERSION

test:
  imports:
    - torcharrow
  source_files:
    - torcharrow/test
  requires:
    - pytest

about:
  home: https://github.com/facebookresearch/torcharrow
  license: BSD
  license_file: LICENSE
  summary: "A torch.Tensor-like DataFrame library supporting multiple execution runtimes and Arrow as a common memory format."
  doc_url: https://github.com/facebookresearch/torcharrow/blob/main/tutorial/tutorial.ipynb
